lib/two_zero_four_eight_web/router.ex
defmodule TwoZeroFourEightWeb.Router do
  use TwoZeroFourEightWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", TwoZeroFourEightWeb do
    pipe_through :browser

    get("/", GameController, :index)
    resources("/games", GameController, only: [:create, :show])
  end
end

lib/two_zero_four_eight_web/views/layout_view.ex
defmodule TwoZeroFourEightWeb.LayoutView do
  use TwoZeroFourEightWeb, :view
end

lib/two_zero_four_eight_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
        </nav>
      </section>
    </header>
    <main class="container mt-4">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/two_zero_four_eight_web/templates/layout/game.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/game.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation" class="nav">
            <%= link("Home", to: Routes.game_path(@conn, :index), class: "nav-link") %>
        </nav>
      </section>
    </header>
    <main class="container mt-4">
      <%= @inner_content %>
    </main>
  </body>
</html>